### ISSUE TITLE
[Suggestion] End place structure world spawn

### ISSUE THREAD

**Issue by pjc21** [maruohon/worldprimer#5]
Issue when using the place structure command and spawn for pos in a world that uses WorldProviderEnd or extends it, 

I am trying to place structures in an end dimension by first setting a random spawn point, then using place structure command
- worldprimer-dim-command-nth 1 11 commandtosetrandomspawn <dimid>  //spawn is set using sender.getEntityWorld().setSpawnPoint(pos);
- worldprimer-dim-command-nth 1 11 worldprimer place-structure {SPAWN_X} {SPAWN_Y} {SPAWN_Z} structurename

this works fine with other providers however with the end provider while the player will spawn at the new random spawn point the structure will still be created at the default spawn for 
end provider as getSpawnCoordinate() will always return BlockPos(100, 50, 0).

was hoping you could add in a config option to getspawnpoint() instead of getSpawnCoordinate() from WorldUtils 

maybe like

```
public static BlockPos getWorldSpawn(World world)
{
	BlockPos spawn = null;

	if(Config.getspawnpointfromEnd)
	{
		spawn = world.getSpawnPoint();
	}
	else
	{
		if (world instanceof WorldServer)
		{
			spawn = ((WorldServer) world).getSpawnCoordinate();
		}

		if (spawn == null)
		{
			spawn = world.getSpawnPoint();
		}
	}
    return spawn;
}
```

**Comment by maruohon** [comment]
There are now new substitutions that don't consider the getSpawnCoordinate() at all: `{SPAWN_POINT_X}` etc.
